replicaCount: 1

quarkus:
  - name: quarkus
    image:
      repository: ghcr.io/forsakringskassan/template-quarkus-app
      tag: snapshot
    properties: |
      fullmakts.api.base-url=http://whatever/

      quarkus.http.port=8080
      quarkus.http.host=0.0.0.0
      quarkus.log.level=INFO
      quarkus.log.console.enable=true
      quarkus.health.enabled=true
      quarkus.health.openapi.included=true

apache:
  - name: apache
    image:
      repository: ghcr.io/forsakringskassan/designsystem-user-app
      tag: snapshot

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
  hosts:
    - paths:
        - path: /api
          pathType: Prefix
          backend: quarkus
        - path: /
          pathType: Prefix
          backend: apache

